### ISSUE TITLE
Installation instructions are unclear

### ISSUE THREAD

**Issue by stefsmeets** [KVSlab/VaMPy#104]
Hi, I'm trying to install vampy on my machine, but I keep running into issues. Eventually I got it to work by trying this on Linux. So I'm wondering:

- Which platforms are supported?
- Which version of Python do I need?
- What libraries do I need to install to get this to work?

It is not clear in the readme which OS and python versions are supported. The documentation says it can be installed via pip, so I naively tried to install via pip (python 3.10) on Windows (`pip install vampy`), but this did not work. If there is a version available on pypi, it would be great if the project page could be linked in the readme.

Then I cloned the repo and installed via `pip install .`. This failed the tests, because I needed `dolfin`.

This time I followed the installation instructions, and it turns out that I was also not able to install this using `conda`.

```
PS > conda env update --file environment.yml --name your_environment
Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound:
  - fenics
```

I then tried on linux, and this takes a very long time to install:

```
$ conda env update --file environment.yml --name your_environment
```

Eventually it did something and it seems to work.

**Comment by hkjeldsberg** [comment]
Dear @stefsmeets ,

Thank you for highlighting this issue. It sounds like there were some trouble installing vampy on your machine. I have tried to address most of your comments through PR #107.
In summary, here are some key points regarding the installation of Vampy:

* Platform Support: Vampy can be installed on any operating system that supports Python, including Windows, macOS, and Linux.  On Linux and macOS, Vampy can be installed using conda or through the docker image. On Windows, it is a bit more complicated due to the FEniCS dependency. We recommend using the docker image for Windows, although there are workarounds for installing FEniCS.

* Python Version: Vampy requires Python 3.8 or higher.

* Required Libraries: The major dependencies for Vampy are FEniCS, Oasis, and morphMan. Additionally, there are some minor dependencies such as paramiko, cppimport, and matplotlib, which can be installed using either pip or conda.

I hope this, and the changes to the documentation in PR #107 will clarify the installation process of VaMPy. 

Best regards,
Henrik

**Comment by stefsmeets** [comment]
Thanks!
