### ISSUE TITLE
`compute_hemodynamic_indices.py` not running properly with multiple cores

### ISSUE THREAD

**Issue by keiyamamo** [KVSlab/VaMPy#60]
Hi,

I found out that the `compute_hemodynamic_indices.py` does not run properly when using more than two cores.
I have not figured out what is causing the problem, but will investigate and report it here. 
`WSS` looks fine but other indices may not be correct (for example, containing none values).

**Comment by hkjeldsberg** [comment]
Hi @keiyamamo ,

Thanks for reporting the issue! I am having similar issues, and I'm suspecting it might be related to the `get_dabla_function()` method defined at the end of the script, or specifically when evaluating the `dabla` function. Have you made any progress since you reported the issue? 

Best,
Henrik

**Comment by keiyamamo** [comment]
Hi @hkjeldsberg,

I’m also pretty sure that it’s debla function! However, I do not have any updates on this :(
