### ISSUE TITLE
Error when running demo case

### ISSUE THREAD

**Issue by keiyamamo** [KVSlab/VaMPy#77]
Hi @hkjeldsberg 

I just re-downloaded VamPy and faced an issue when running the test case. I think the problem is that `inlet_id` and `outlet_id` are all -1 in json file (see the attached screenshot), which later produces an error when creating boundary conditions. Could you maybe look into this problem?

![Screen Shot 2022-10-24 at 12 47 47](https://user-images.githubusercontent.com/42674006/197509537-621636fc-336e-4b17-b17e-d135c6b9a61c.png)

**Comment by hkjeldsberg** [comment]
Hi @keiyamamo 

Thanks for reporting this! Did you experience this for the Artery model? 
I have seen similar issues in the past, but I believe they have been fixed in later versions of Vampy / morphMan. Did you try updating to the latest version of [morphman](https://github.com/KVSlab/morphMan)?  

Best,
Henrik

**Comment by keiyamamo** [comment]
Hi @hkjeldsberg,

Yes it's artery case! I haven't updated morphman long time, so I'll try it again with updated version of morphman!
Thanks for the help.

**Comment by keiyamamo** [comment]
Updating `morphman` solved the issue! Thanks for the help @hkjeldsberg
